### ISSUE TITLE
Cookie returned even when login unsuccessful

### ISSUE THREAD

**Issue by mjiang108** [bluesproutllc/instaTrainer#6]
Please review this @Linhatran 

**Describe the bug**
Cookie returned even when login unsuccessful.

**To Reproduce**
1. Send post request to api/auth/signin with nonexisting username. Receive cookie and "user not found"
2. Also try to send post request to api/auth/signin with existing username but wrong password. Receive cookie and "logged in"

**Expected behavior**
No cookie returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/9983876/107591769-30b51a00-6bc0-11eb-950d-d5f52cec34db.png)
![image](https://user-images.githubusercontent.com/9983876/107591910-7a9e0000-6bc0-11eb-9755-c3ae6c1ee69a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by Linhatran** [comment]
Hi @mattljiang 
Thank you for your promptly notification. I have fixed the issue by modifying these codes below: 

**Issue 1: backend did not send appropriate response when an user inputs wrong password** 
- Reason: there was only one conditional to check if the username exists in the database: `res.locals.status === 'not found' `
- Solution: I added another conditional to make it more complete with `res.locals.status === 'not found' || res.locals.status === false`. Now either username or password is wrong, frontend will receive a 409 status code and text 'username or password not found'
<img width="572" alt="Screen Shot 2021-02-10 at 7 19 56 PM" src="https://user-images.githubusercontent.com/41355392/107593443-f9049d00-6bd4-11eb-9606-40d014f34b4c.png">

**Issue 2: cookies were sent back even if credentials were invalid** 
- Reason: there was no conditional statement to check if user logged in or not, cookies were sent regardless via `res.cookies` in one of the controllers
- Solution: Added a conditional to check the login status, if there was a status of 'not found' or 'username taken' meaning login failed, move on to the next middleware, otherwise, send back cookies
<img width="583" alt="Screen Shot 2021-02-10 at 7 27 49 PM" src="https://user-images.githubusercontent.com/41355392/107593862-11c18280-6bd6-11eb-8145-a8819b54f4a5.png">

I will submit a PR tonight to update the latest codes. Thanks again, Matt!
